# Generated by Django 4.0.4 on 2022-04-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_docs_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='user',
        ),
    ]
